name: Build

on: [push, release, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
            
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...
      
    - id: docker-tag
      uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io 
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.5.0
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.docker-tag.outputs.tag }}
